export declare const colors: {
    primary: string;
    primaryDark: string;
    primaryLight: string;
    primaryLightest: string;
    secondary: string;
    secondaryDark: string;
    secondaryLight: string;
    secondaryLightest: string;
    white: string;
    black: string;
    gray: string;
    grayLight: string;
    grayDarker: string;
    grayDarkest: string;
    information: string;
    informationLight: string;
    informationLightest: string;
    focus: string;
    attention: string;
    positive: string;
    error: string;
    informative: string;
};
