name: Run CI at @crimson-ui/react

on:
  push:
    branches:
      - master
    paths:
      - 'packages/react/**'
      - 'packages/styles/**'
      - 'packages/web/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/react/**'
      - 'packages/styles/**'
      - 'packages/web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and build
        run: |
          node --version
          yarn --version
          yarn --frozen-lockfile
          yarn build
