name: Run CI at @crimson-ui/styles

on:
  push:
    branches:
      - master
    paths:
      - 'packages/styles/**'
      - 'packages/web/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/styles/**'
      - 'packages/web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies and build
        run: |
          node --version
          yarn --version
          yarn --frozen-lockfile
          yarn build
