name: 'STYLES_CI'

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  paths:
    - 'packages/styles/**'
    - 'packages/web/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install
      - run: npm build
