name: Run CI at @crimson-ui/web

on:
  push:
    branches:
      - master
    paths:
      - 'packages/colors/**'
      - 'packages/web/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/colors/**'
      - 'packages/web/**'

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hasFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies and build
        run: |
          node --version
          yarn --version
          yarn --frozen-lockfile
          yarn build
